// app/layout.js
import "../app/styles/globals.css";
import I18nProvider from "../components/Providers/I18nProvider";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { detectLanguage } from "@/lib/language-detector";
import { Zain } from "next/font/google";

const zain = Zain({
  subsets: ["latin"],
  weight: ["200", "300", "400", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Detect language on server side
  const lng = await detectLanguage();

  return (
    <html
      lang={lng}
      dir={lng === "ar" ? "rtl" : "ltr"}
      className={zain.className}
    >
      <body>
        <Navbar />
        <main className="">
          <I18nProvider lng={lng}>{children}</I18nProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
