import { Geist, Geist_Mono } from "next/font/google";
import "../app/styles/globals.css";
import I18nProvider from "../components/Providers/I18nProvider";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { Zain } from 'next/font/google';

const zain = Zain({
  subsets: ['latin'],
  weight: [ '200', '300', '400', '700', '800', '900'],
});
// import i18n from "../lib/i18n";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Waslah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="">
          <I18nProvider>
            {children}
          </I18nProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
